### ISSUE TITLE
Suggestion: holding a shield also affects hunger

### ISSUE THREAD

**Issue by vivagabe** [JMPotionwiz/Armorers-Bane-Mod#1]
As the title says. Great mod! sorry didnt know how else to offer suggestion.

**Comment by JMPotionwiz** [comment]
Thanks! And thank you for the feedback as well, that sounds like a pretty good idea.

**Comment by JMPotionwiz** [comment]
Aaaaannnd done! Shields now drain hunger when held. Thank you for the suggestion!
